reiple/Collab

- src/main/java/collab/CommandIF.java
- src/main/java/collab/EmployeeManager.java
- src/main/java/collab/FirstOptionIF.java
- src/main/java/collab/SecondOptionIF.java
- src/main/java/collab/ThirdOptionIF.java
- Add employee manager class
- Add command interface
- Add option interface
> [Feat] add employee manager, command/option interface

- src/main/java/collab/Employee.java
- src/test/java/collab/EmployeeTest.java
사원 정보를 저장 및 접근 하기 위한  Employee 클래스추가
해결: Employee Class 정의 #6
> [Feat] Employee 클래스 추가

- build.gradle
- src/main/java/collab/options/second/FamilyNameSearchOption.java
- src/test/java/collab/options/Columns.java
- src/test/java/collab/options/second/FamilyNameSearchOptionTest.java
성명 중 성으로 검색하는 옵션 TDD 및 Mock을 이용한 기능 구현
참조: #7
> [Feat] 성명의 성으로 검색하는 옵션 테스트 (Mock 생성)

- src/main/java/collab/AbstractCommand.java
- src/main/java/collab/AbstractFirstOption.java
- src/main/java/collab/AbstractSecondOption.java
- src/main/java/collab/AbstractThirdOption.java
- src/main/java/collab/AddCommand.java
- src/main/java/collab/CommandIF.java
- src/main/java/collab/DeleteCommand.java
- src/main/java/collab/EmployeeDAO.java
- src/main/java/collab/FirstOptionIF.java
- src/main/java/collab/ICommand.java
- src/main/java/collab/Main.java
- src/main/java/collab/ModifyCommand.java
- src/main/java/collab/SearchCommand.java
- src/main/java/collab/SecondOptionIF.java
- src/main/java/collab/ThirdOptionIF.java
- src/main/java/collab/options/first/EmptyFirstOption.java
- src/main/java/collab/options/first/NoneFirstOption.java
- src/main/java/collab/options/first/PrintOption.java
- src/main/java/collab/options/second/DayOfBirthdayOption.java
- src/main/java/collab/options/second/LastNameOption.java
- src/main/java/collab/options/second/LastPhoneNumberOption.java
- src/main/java/collab/options/second/MiddlePhoneNumberOption.java
- src/main/java/collab/options/second/MonthOfBirthdayOption.java
- src/main/java/collab/options/second/NoneSecondOption.java
- src/main/java/collab/options/second/YearOfBirthdayOption.java
- add default empty classes as UML draft version
> [Feat] Add default empty classes

- src/main/java/collab/Employee.java
- src/test/java/collab/EmployeeTest.java
String Pattern Matchin지원을 위해 일부 변수 Type String 변경
해결: Employee Class Type 변경 #14
> [Fix] Employee Class type 수정

- eclipse-java-google-style.xml
- intellij-google-code-style.xml
https://tychejin.tistory.com/334를 참고하여 IntelliJ에서 구글 코딩 스타일 반영이 가능합니다.
코딩 스타일 설정에 대한 파일입니다.
참고: #4
> [Style] IntelliJ용 구글 코딩스타일 반영

- src/main/java/collab/DataBase.java
- src/test/java/collab/DeleteTest.java
- src/test/java/collab/ModifyTest.java
- src/test/java/collab/SearchTest.java
옵션에 따른 ADD/MODIFY/SELECT/DELETE에 대한 DATABASE 기능을 구성했습니다.
객체화 하여 수정 필요하며, TEST도 작성하였습니다.
> [FEAT] 옵션에 따른 ADD/MODI/SEL/DEL 기능과 TEST, 객체화 필요

- src/main/java/collab/AbstractSecondOption.java
- src/main/java/collab/EmployeeDAO.java
- src/main/java/collab/options/second/LastPhoneNumberOption.java
- src/main/java/collab/options/second/MiddlePhoneNumberOption.java
- src/test/java/collab/options/second/FirstNameSearchOptionTest.java
- src/test/java/collab/options/second/LastNameSearchOptionTest.java
- src/test/java/collab/options/second/LastPhoneNumberOptionTest.java
- src/test/java/collab/options/second/MiddlePhoneNumberOptionTest.java
전화번호 중간 자리 및 뒷 자리 검색을 위한 옵션 2 구현
참고: #20
> [Feat] 전화번호 검색을 위한 옵션 구현

- src/test/java/collab/options/second/FirstNameSearchOptionTest.java
- src/test/java/collab/options/second/LastNameSearchOptionTest.java
Employee 클래스의 생성자가 변경되어 기존에 동작하던 테스트 케이스가 동작하지 않아 수정하였습니다.
참고: #7
> [Fix] 변경된 Emplyoee 생성자에 맞춰서 테스트 객체 수정

- src/main/java/collab/CommandParser.java
- src/main/java/collab/options/second/EmptySecondOption.java
- src/main/java/collab/options/third/NoneThirdOption.java
- src/test/java/collab/CommandParserTest.java
- Add empty parser class
- Implement testcases command parser
- Add EmptySecondOption class
- Add NoneThirdOption class
> [Feat] Implement testcases for parser

- src/main/java/collab/options/first/PrintOption.java
- src/test/java/collab/options/first/PrintOptionTest.java
Print Option Class 구현 Pull Request
- Emloyee list 입력 후, realEmployeeNumber 기준으로 정렬 후 결과 String 반환.
- Employee 갯수에 따른 Test Case 추가
> [Feat] Print Option Class 구현

- src/main/java/collab/options/second/MiddlePhoneNumberOption.java
* Merge로 인해 main에 합쳐지지 않은 import문 추가
* Test 실행 안되는 문제 해결
> [Fix] merge 과정에서 삭제된 import문으로 인한 코드 이상 정상화

- src/main/java/collab/AddCommand.java
- src/main/java/collab/CommandParser.java
- src/main/java/collab/DeleteCommand.java
- src/main/java/collab/ModifyCommand.java
- src/main/java/collab/SearchCommand.java
- src/main/java/collab/options/second/DayOfBirthdayOption.java
- src/main/java/collab/options/second/EmptySecondOption.java
- src/main/java/collab/options/second/LastNameOption.java
- src/main/java/collab/options/second/LastPhoneNumberOption.java
- src/main/java/collab/options/second/MiddlePhoneNumberOption.java
- src/main/java/collab/options/second/MonthOfBirthdayOption.java
- src/main/java/collab/options/second/NoneSecondOption.java
- src/main/java/collab/options/second/YearOfBirthdayOption.java
- src/test/java/collab/CommandParserTest.java
- Implement command parser
- 각 Command Class 의 생성자를 필요 option 만 받도록 수정
- FirstOption, SecondOptoin 을 추후 PrintOption, SearchOption 으로 수정 필요함.
> [Feat] Implement command parser

- README.md
* 팀 프로젝트 진행 결정 사항 정리 (readme.md)
> [Docs] 팀 프로젝트 진행을 위해 결정한 사항 업데이트

- src/main/java/collab/EmployeeDAO.java
- src/main/java/collab/EmployeeManager.java
- src/main/java/collab/IDAO.java
- src/main/java/collab/options/second/DayOfBirthdayOption.java
- src/main/java/collab/options/second/FirstNameOption.java
- src/main/java/collab/options/second/LastNameOption.java
- src/main/java/collab/options/second/LastPhoneNumberOption.java
- src/main/java/collab/options/second/MiddlePhoneNumberOption.java
- src/main/java/collab/options/second/MonthOfBirthdayOption.java
- src/main/java/collab/options/second/YearOfBirthdayOption.java
- src/test/java/collab/options/second/DayOfBirthdayOptionTest.java
- src/test/java/collab/options/second/FirstNameOptionTest.java
- src/test/java/collab/options/second/FirstNameSearchOptionTest.java
- src/test/java/collab/options/second/LastNameOptionTest.java
- src/test/java/collab/options/second/LastNameSearchOptionTest.java
- src/test/java/collab/options/second/LastPhoneNumberOptionTest.java
- src/test/java/collab/options/second/MiddlePhoneNumberOptionTest.java
- src/test/java/collab/options/second/MonthOfBirthdayOptionTest.java
- src/test/java/collab/options/second/YearOfBirthdayOptionTest.java
- DAO interface 를 통해서 database 수정
- 우선은 single field 검색만 지원
- DAO 및 database 기본 기능 구현 이후 추후 확장 고려
- DAO 내 getAll() 함수를 getAllItems() 로 수정하고 관련 부분을 전부 refactor 하였습니다.
> [Feat] DAO interface 생성

- src/main/java/collab/Employee.java
- src/test/java/collab/EmployeeTest.java
Employee input validation 관련 코드 작성하였습니다.
함수 추가로 가독성이 떨어졌는데, 추후 리팩토링 하겠습니다.
issue: https://github.com/reiple/Collab/issues/19
> [Feat] employee input validation 구현

- src/main/java/collab/options/first/PrintOption.java
- src/test/java/collab/options/first/PrintOptionTest.java
Print Option 반환 마지막 개행문자 삭제 및  0개일때 "NONE" 반환으로 변경
issue: https://github.com/reiple/Collab/issues/36
> [Fix] PrintOption 출력 수정

- src/test/java/collab/ModifyTest.java
- src/test/java/collab/SearchTest.java
- src/test/java/collab/options/second/FirstNameSearchOptionTest.java
- src/test/java/collab/options/second/LastNameSearchOptionTest.java
* Employee 클래스의 Validation 체크 추가로 인해 exception 발생하는 문제 해결
* Unit Test에서 Employee 객체 생성 시, 잘못된 값을 넣는 경우를 assertThrow를 이용하여 예외 발생 여부 체크 추가함
> [Fix] Employee 클래스의 valid 체크 추가로 인한 Unit Test 실행 불가 수정

- .github/workflows/sonar-check.yml
- build.gradle
* PR 작성마다 Sonarqube 체크 결과를 자동으로 첨부함
* Sonarqube 체크 결과 Success/Fail과 관계 없이 merge 가능
* 수업 시간에 배운 Refactor 항목들 자동 체크 (잘못 체크되는 경우도 있음)
* 아래와 같은 모양의 체크 결과가 PR에 comment로 자동 작성됨
> [Style] Sonar Cloud 체크를 위한 설정

- src/main/java/collab/AbstractColumn.java
- src/main/java/collab/DataBase.java
- src/main/java/collab/EmployeeDAO.java
- src/main/java/collab/IDAO.java
- src/main/java/collab/columnList/Birthday.java
- src/main/java/collab/columnList/Certi.java
- src/main/java/collab/columnList/Cl.java
- src/main/java/collab/columnList/EmployeeNum.java
- src/main/java/collab/columnList/Name.java
- src/main/java/collab/columnList/PhoneNum.java
- src/test/java/collab/DeleteTest.java
- src/test/java/collab/ModifyTest.java
- src/test/java/collab/SearchTest.java
IF에 맞게 수정하여 TEST 시 정상 확인했습니다.
Option1/2 전달에 따른 조회 방식 및 UPDATE해야하는 컬럼 객체화 필요합니다.
일단,
동작은 가능하도록 해놨습니다.
특이사항 없으면, 리팩토링 하겠습니다.
> [Sytle] IF에 맞게 수정, Option1/2 전달 방식 및 Update Column별 객체화 필요

- src/main/java/collab/ModifyCommand.java
- src/main/java/collab/SearchCommand.java
- src/main/java/collab/options/first/PrintOption.java
- src/test/java/collab/EmployeeManagerTest.java
- src/test/java/collab/ModifyCommandPhoneNumberTest.java
- src/test/java/collab/ModifyTest.java
- src/test/java/collab/SearchTest.java
* IDAO 관련 코드 에러 수정
* FileManager 미구현으로 인한 null exception 해결을 위해 mock 추가
> [Fix] IDAO에서 null이 리턴되는 것 임시 조치 및 FileManager 관련 mock 생성

- src/test/java/collab/SearchTest.java
유효하지 않은 Input으로 인해 TC가 FAIL되어,
유효한 Input(하지만 DB에는 없는 정보)으로 수정하였습니다.
> [Fix] 유효하지 않은 Input 정보 수정

- src/main/java/collab/AddCommand.java
- src/test/java/collab/AddCommandTest.java
> [Feat] Add command 구현

- src/main/java/collab/EmployeeManager.java
- src/main/java/collab/FileManager.java
- src/test/java/collab/EmployeeManagerTest.java
- src/test/java/collab/FileManagerTest.java
- FileManager testcase 작성
- FileManager 구현
- EmployeeManager 연동
> [Feat] FileManager 구현

- src/main/java/collab/CommandParser.java
hashmap type 에러 fix
footer: https://github.com/reiple/Collab/issues/50
> [Fix] command parser hashmap type fix

- src/main/java/collab/AbstractCommand.java
- src/main/java/collab/CommandParser.java
- src/main/java/collab/EmployeeManager.java
- src/main/java/collab/ICommand.java
- src/main/java/collab/ModifyCommand.java
- src/main/java/collab/SearchCommand.java
- src/main/java/collab/options/first/PrintOption.java
- src/test/java/collab/EmployeeManagerTest.java
- src/test/java/collab/ModifyCommandPhoneNumberTest.java
- src/test/java/collab/SearchCommandNameTest.java
- src/test/java/collab/options/first/PrintOptionTest.java
> [Refactoring] PrintOption 개행문자 변경

- src/main/java/collab/Employee.java
- src/main/java/collab/ModifyCommand.java
- src/main/java/collab/SearchCommand.java
- src/main/java/collab/options/second/EmptySecondOption.java
- src/test/java/collab/EmployeeTest.java
- src/test/java/collab/ModifyCommandPhoneNumberTest.java
- src/test/java/collab/SearchCommandNameTest.java
기존 main branch 호환성을 위해 
branch 재작성하였습니다.
그리고 getFiled 함수 호환성을 위해 whitebox 처리하였습니다.
아울러, 현재 ModifyCommandPhoneNumberTest, SearchCommandnameTest에서 fail 발생하는데 확인 부탁드립니다.
> Dev emptysecondoption re

- src/main/java/collab/Main.java
- Test code 는 따로 구현하지 않음
- EmployManager 내 File to File 최종 test 존재. 리팩토리시 수정 필요.
> [Feat] Main client code 구현

- build.gradle
* Gradle을 이용한 Executable Jar 생성 설정
* intelliJ에서
* 메뉴 > View > Tool Windows > Gradle 선택
* Gradle 창에서 Tasks > build > jar 더블클릭
* Terminal
* ./gradlew jar
* build/libs/Collab-1.0.0-SNAPSHOT.jar 파일이 생성됨
* java -jar <JAR파일명> <인자>
* build.gradle 파일 내에 version 뒤쪽에 있는 문자열이 파일명으로 그대로 출력됩니다.
> [Style] Executable Jar 생성 설정

- src/main/java/collab/DataBase.java
- src/test/java/collab/DeleteTest.java
- src/test/java/collab/ModifyTest.java
- src/test/java/collab/SearchTest.java
> [Style] DAO Return 모두 동일하게 처리, 불필요 추상CLASS 삭제 및 SornarCloud 개정

- src/main/java/collab/DataBase.java
- src/test/java/collab/DeleteTest.java
- src/test/java/collab/ModifyByConditionTest.java
- src/test/java/collab/ModifyByIDTest.java
- src/test/java/collab/SearchTest.java
> [Fix] DataBase employee Modify 시 변경 안됨 수정 및 TC 추가

- src/main/java/collab/CommandParser.java
- src/main/java/collab/EmployeeManager.java
- src/main/java/collab/options/first/EmptyFirstOption.java
- src/main/java/collab/options/first/NoneFirstOption.java
- src/main/java/collab/options/first/PrintOption.java
- src/test/java/collab/CommandParserTest.java
- src/test/java/collab/DeleteCommandBirthdayTest.java
- src/test/java/collab/EmployeeManagerTest.java
- src/test/java/collab/ModifyCommandEmployeeTest.java
- src/test/java/collab/ModifyCommandPhoneNumberTest.java
- src/test/java/collab/SearchCommandBirthdayTest.java
- src/test/java/collab/SearchCommandCareerLevelTest.java
- src/test/java/collab/SearchCommandCertiTest.java
- src/test/java/collab/SearchCommandEmployeeNumTest.java
- src/test/java/collab/SearchCommandNameTest.java
- src/test/java/collab/SearchCommandPhoneNumberTest.java
- System.linesperator() 로 교체
- EmployeeManager test 케이스 bug fix 및 에러 처리 강화
- 사용안하는 옵션은 NoneFirstOption, 비어 있는 옵션은 EmptyFirstOption 으로 교체
> [Fix] Command Result 개행 문자 정리
